### ISSUE TITLE
Smooth Scrolling Plugin seems broke some external URLs with #

### ISSUE THREAD

**Issue by alexsuslin** [AtlassianPS/AtlassianPS.github.io#29]
### Expectation
Go to webpage https://atlassianps.org/docs/Contributing/
and click on Homepage link under thank you quoted message

### Status Quo
I am expecting to be redirected to https://atlassianps.org/#people, however the link is not working on chrome and edge browsers

### My suggestion
` $('a[href*="#"]:not([href="#"]), a.inpage-navigation[href*="#"]').on('click', function (event) {
        event.preventDefault();
        smoothScroll($(this.hash));
    });`

change to 
` $('a[href^="#"]:not([href="#"]), a.inpage-navigation[href*="#"]').on('click', function (event) {
        event.preventDefault();
        smoothScroll($(this.hash));
    });`

in the theme.js file, as I bet smooth scroll broke such URLs

**Comment by lipkau** [comment]
fixed in #30
